[workspace]
members = [
    "logic",
    "server",
    "client",
]
exclude = [".cargo"]
resolver = "3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
