apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-dealer
  labels:
    app.kubernetes.io/name: blackjack-dealer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blackjack-dealer
  template:

