---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: blackjack-strip-ingress
  namespace: blackjack
  labels:
    app.kubernetes.io/managed-by: manual
spec:
  stripPrefix:
    prefixes:
      - /blackjack
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blackjack-dealer
  namespace: blackjack
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/blackjack`)
      middlewares:
        - name: blackjack-strip-ingress
          namespace: blackjack
      services:
        - kind: Service
          name: blackjack-dealer
          namespace: blackjack
          port: 1337
          passHostHeader: true
