name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_VERSION: 1.89.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: Checkout code
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install $RUST_VERSION --profile minimal
          rustup component add rustfmt clippy --toolchain $RUST_VERSION
          rustup show
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
